name: Update Windsurf Formula

on:
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight
  workflow_dispatch:

jobs:
  update-formula:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq

      - name: Fetch Latest Version and SHA256
        run: |
          # Fetch the metadata from the API
          API_RESPONSE=$(curl -s "https://windsurf-stable.codeium.com/api/update/darwin-arm64-dmg/stable/latest")
          
          # Extract information using jq
          DMG_URL=$(echo "$API_RESPONSE" | jq -r .url)
          VERSION=$(echo "$API_RESPONSE" | jq -r .windsurfVersion)
          SHA256=$(echo "$API_RESPONSE" | jq -r .sha256hash)
          
          echo "DMG_URL=$DMG_URL" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "SHA256=$SHA256" >> $GITHUB_ENV

      - name: Update Cask File
        run: |
          # Create a temporary file with the new content
          cat > Casks/windsurf.rb.new << EOL
          cask "windsurf" do
            version "$VERSION"
            sha256 "$SHA256"
          
            url "$DMG_URL",
                verified: "windsurf-stable.codeiumdata.com/"
            name "Windsurf"
            desc "Windsurf Editor by Codeium"
            homepage "https://codeium.com/windsurf"
          
            auto_updates true
          
            app "Windsurf.app"
          end
          EOL
          
          # Replace the old file with the new one
          mv Casks/windsurf.rb.new Casks/windsurf.rb

      - name: Commit Changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add Casks/windsurf.rb
          git commit -m "Update Windsurf cask to version $VERSION"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

