name: Validate Windsurf Formula

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  validate-formula:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          eval "$(/opt/homebrew/bin/brew shellenv)"

      - name: Build and Install Windsurf Formula
        run: |
          brew install --build-from-source Formula/windsurf.rb

      - name: Test Windsurf Installation
        run: |
          windsurf --version
          windsurf --help
